version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@architect/architect"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@architect/architect"
    versions:
    - 8.4.10
    - 8.4.11
    - 8.4.7
    - 8.4.8
    - 8.4.9
    - 8.5.0
    - 8.5.1
    - 8.5.2
    - 8.5.3
    - 8.5.4
    - 8.5.5
    - 8.5.6
    - 8.5.7
    - 8.5.8
  - dependency-name: svgo
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.3
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.3.0
  - dependency-name: ini
    versions:
    - 1.3.8
