#!/bin/bash
# Checks if last commit message was semver
# - If so, deploy to production
# - And always deploy to staging
# - (Kinda like a Begin app)
TAG=`git log -1 --pretty=%B`
if echo "$TAG" | grep '^\([0-9]\{1,\}\.\?\)\{3\}'; then
  npx deploy --production
  NODE_ENV=production scripts/reset-assets
fi
npx deploy --staging
NODE_ENV=staging scripts/reset-assets
