#!/bin/sh

# get root deps installed
npm i

# install lambda deps
for f in `ls src/css`
do
  cd "src/css/$f" &&
  npm i --production &&
  cd ../../../ &
done
wait 

for f in `ls src/html`
do
  cd "src/html/$f" &&
  npm i --production &&
  cd ../../../ &
done
wait
